---

- name: show run
  connection: network cli
  gather_facs: false
  hosts: all
  task:
     - name: show run
       ios_command:
          commands:
             - show run
       register: config
	  
	  
