---
# This playbook runs a basic DF command.

- hosts: all

  tasks:
  - name: find disk space available.
    ios_command:
    commands: show version
    
  - name: run show version and check to see if output contains IOS
    ios_command:
    commands: show version
    wait_for: result[0] contains IOS
      
      
      
